blank_issues_enabled: true
contact_links:
  - name: Not a filter issue
    url: https://github.com/lassekongo83/Frellwits-filter-lists/discussions
    about: This is for questions or general discussions about the filters in this repository.
  - name: Other issues or questions about uBlock Origin that doesn't have anything to do with these filters
    url: https://old.reddit.com/r/uBlockOrigin/
    about: For general support, questions, or help about uBlock Origin.
